on:
  # Indicates I want to run this workflow on all branches, PR, and tags
  push:
    branches: [ "main", "draft" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

env:
  RUST_VERSION: 1.93.0
  BIN_NAME: "wstunnel"

jobs:
  build:
    name: Build - ${{ matrix.platform.name }}
    # By default, runs on Ubuntu, otherwise, override with the desired os
    runs-on: ${{ matrix.platform.os || 'ubuntu-24.04' }}
    strategy:
      fail-fast: false
      matrix:
        # Set platforms you want to build your binaries on
        platform:
          # Linux
          - name: Linux x86_64
            target: x86_64-unknown-linux-musl
            build-args: "--release --features=jemalloc"

          - name: Linux aarch64
            target: aarch64-unknown-linux-musl
            build-args: "--release --features=jemalloc -vv"

    steps:

      - name: Install package for linux
        if: contains(matrix.platform.target, 'linux')
        run: sudo apt install musl-tools

      - name: Checkout Git repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      # Linux
      - name: Install rust toolchain for Linux
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1
        with:
          # We setup Rust toolchain and the desired target
          profile: minimal
          toolchain: "${{ env.RUST_VERSION }}"
          override: true
          target: ${{ matrix.platform.target }}
          components: rustfmt, clippy

      - name: Install bindgen-cli
        run: cargo install bindgen-cli

      - name: Install taplo-cli
        run: cargo install taplo-cli --locked

      - name: Show command used for Cargo
        run: |
          echo "cargo command is: ${{ env.CARGO }}"
          echo "target flag is: ${{ env.BUILD_ARGS }}"

      - name: Build ${{ matrix.platform.name }} binary
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1
        env:
          JEMALLOC_SYS_WITH_LG_PAGE: ${{ contains(matrix.platform.target, 'aarch64') && '14' || '12' }}
        # We use cross-rs if not running on x86_64 architecture on Linux
        with:
          command: build
          use-cross: ${{ !contains(matrix.platform.target, 'x86_64') }}
          args: ${{ matrix.platform.build-args }} --bin wstunnel --target ${{ matrix.platform.target }}

      - name: Store artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          # Finally, we store the binary as GitHub artifact for later usage
          name: ${{ env.BIN_NAME }}-${{ matrix.platform.target }}
          path: target/${{ matrix.platform.target }}/release/${{ env.BIN_NAME }}
          retention-days: 1
